// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrzyW5VyGNsVjgItLsGmbZMSaixqhCREM',
    appId: '1:123460780273:web:05f85b468bdfd505eea950',
    messagingSenderId: '123460780273',
    projectId: 'chatapp-4679a',
    authDomain: 'chatapp-4679a.firebaseapp.com',
    storageBucket: 'chatapp-4679a.appspot.com',
    measurementId: 'G-4R2XTSEE8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe2QHcIK1bs9IX2YK5O2yf4NzObFHmv90',
    appId: '1:123460780273:android:206660ab8b9a0edceea950',
    messagingSenderId: '123460780273',
    projectId: 'chatapp-4679a',
    storageBucket: 'chatapp-4679a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkTEqNHDCOzMYQiOHqFNzRztGkJj2Thg',
    appId: '1:123460780273:ios:c997519e08d0eb8aeea950',
    messagingSenderId: '123460780273',
    projectId: 'chatapp-4679a',
    storageBucket: 'chatapp-4679a.appspot.com',
    iosBundleId: 'com.example.firebaseAppChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJkTEqNHDCOzMYQiOHqFNzRztGkJj2Thg',
    appId: '1:123460780273:ios:2315235b74dddf47eea950',
    messagingSenderId: '123460780273',
    projectId: 'chatapp-4679a',
    storageBucket: 'chatapp-4679a.appspot.com',
    iosBundleId: 'com.example.firebaseAppChat.RunnerTests',
  );
}
